### ISSUE TITLE
Issue in Debian Docker "fusermount: fuse device not found, try 'modprobe fuse' first " 

### ISSUE THREAD

**Issue by lampchris** [pcloudcom/console-client#146]
Hello, 
I have build a docker container based on ubuntu:18.04 and i have compiled in successfully  the console-client from git.

But, when i run pcloudcc in the docker, i get the following error message:

$ pcloudcc -u my@username.com -p -s -n
pCloud console client v.2.0.1
Please, enter password
...
**fusermount: fuse device not found, try 'modprobe fuse' first**
Down: Everything Downloaded| Up: Everything Uploaded, status is SCANNING
Down: Everything Downloaded| Up: Everything Uploaded, status is READY
**fusermount: fuse device not found, try 'modprobe fuse' first** 

After this first launch, i can see in my HOME a new Folder named "pcloudDrive" but without any files or folders. 

Could you can help me for resolving this issue?
Thank in advance
Regards
Lampchris 
[dockerfile.txt](https://github.com/pcloudcom/console-client/files/6880237/dockerfile.txt)

**Comment by sergeyklay** [comment]
The docker container requires privileged mode in order to expose the fuse based file system to the host. You should be able to get things working by replacing it with `--cap-add SYS_ADMIN` like below:
```
docker run -ti --rm \
           --device /dev/fuse \
           --cap-add SYS_ADMIN \
      <image_id/name>
```

Or, if it fails, use `--privileged` flag:
```
docker run -ti --rm --privileged  <image_id/name>
```

**Comment by lampchris** [comment]
Hello Sergeyklay,

great, it's work, thanks for you help. 

bye
Christophe

**Comment by apotek** [comment]
Hi @sergeyklay. I see this is closed, but I am experiencing the same issue, except on standard Debian 10 (not docker). And it doesn't seem to be an issue with privilege, as I am encountering the issue even if I run as root or with sudo. 

```
root@HOST:/home/data/pcloud# pcloudcc -u 'email@example.com' -p -m '/home/data/pcloud'
pCloud console client v.2.0.1
Please, enter password
Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
fusermount: fuse device not found, try 'modprobe fuse' first
Down: Everything Downloaded| Up: Everything Uploaded, status is READY
fusermount: fuse device not found, try 'modprobe fuse' first
```

I did make sure to `apt-get libfuse-dev fuse` as documented during the build phase. 

I can open a new issue, but since this issue was identical, I thought I would just post this here. Thank you.

**Comment by sergeyklay** [comment]
HI @apotek. Make sure that fuse kernel module is loaded correctly. If my memory serves me correctly, this project does not work with the latest version of fuse, in fact the kernel module and pcloud may use different fuse specifications. So I would pay attention to this as well

**Comment by apotek** [comment]
Thank you @sergeyklay . I tried every approach I could. I think the fact that my debian environment is running in virtualization is blocking fuse from loading correctly. (I have full sudo, but the kernel has some limitations due to virtualization... at least this is my non-expert best guess as to why my installed fuse is not cooperating with this client. 

Unfortunately, being able to remote mount my pcloud as a drive in linux is the one make-or-break feature I needed in a storage service. Thus, the search continues :).
